### ISSUE TITLE
Trollproofing War Worlds!

### ISSUE THREAD

**Issue by GloomyxEmpire** [codeka/wwmmo#139]
The game currently has many ways for players such as Darknova to cause unnecessary issues for players. To limit it these simply add player input limitations to discourage trolls.

  1. Limit size of empire names.
  2. Limit amount of text/emojis posted on global and alliance chat at one time.
  3. Limit the amount of times per minute that text can be posted(of same things maybe so real conversations can continue)
  4. Limit the size of alliance names.
  5. Limit the size of customized star names.
  6. Limit the capability to make alts without using an email.

I don't know how he does it but he claims he can so it would be nice to limit his alt access. I don't think it would require too much code changes either so hopefully it can be done sometime.

(edit: formatting)

**Comment by codeka** [comment]
One thing I was thinking of doing is making it so that non-signed-in empires can't chat at all. I'm not sure if that would annoy legitimate users, but I think it would stop quite a lot of griefing since you'd have to at least sign in with an email address to cause trouble and you wouldn't be able to work around a sinbin by just creating a new account.

Those other changes also seem pretty simple, so I'll look into making those. I definitely don't want people's experiences ruined because of one trouble-maker.

Also, if it's really bad, I can always blacklist his device (he seems to play from the same phone, I can see quite a lot of alternate accounts coming from the same phone). If you think it's bad enough to warrant something along those lines, please contact me off-github.

**Comment by codeka** [comment]
Above I've done 1, 2, 4 and 5. 3 and 6 are slightly more complicated so might take an extra day or too.

I've pinged Gremlin to update the server, so I'll keep you posted.

**Comment by GloomyxEmpire** [comment]
This is great. I am glad at least a few of my requests were easily able to be implemented. I think this should promote a  more robust community that doesn't have to deal with trolls as often.

**Comment by codeka** [comment]
Commit b76b76f56ab290de1a8175ec4c956bbfdd6fcdb9 also collapses all white-spaces into a single space (so you can no longer have alliance/star/empire names with newlines in them. And I've also gone through and updated all existing names to conform to the rules.

**Comment by codeka** [comment]
I think this is mostly done now?
